Refactor compile script and start to integrate Node.js actions in compile script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,25 +1,45 @@
 #!/usr/bin/env bash
+
+###################################################################
+#                    SdZ Heroku Buildpack                         #
+#                                                                 #
+#        Authors: Sylvain Mauduit <sylvain.mauduit@simple-it.fr>  #
+#                 Kevin Letord <kevin.letord@simple-it.fr>        #
+#                                                                 #
+###################################################################
+
 # bin/compile <build-dir> <cache-dir>
 
-# fail fast
-set -e
-set -o pipefail
 
-# START CONFIG
+# ----START CONFIG-----------------------------------------------------
+
+# ----Heroku Packages----
 NGINX_VERSION=1.0.11
-PHP_VERSION=5.3.9
-S3_BUCKET=simpleit-heroku-builds
-# END CONFIG
-
-
-#
 NGINX_URL="https://${S3_BUCKET}.s3.amazonaws.com/nginx-${NGINX_VERSION}-heroku.tar.gz"
-PHP_URL="https://${S3_BUCKET}.s3.amazonaws.com/php-${PHP_VERSION}-with-fpm-heroku.tar.gz"
-#
-
 NGINX_PATH="vendor/nginx"
+
+PHP_VERSION=5.3.9
+PHP_URL="https://${S3_BUCKET}.s3.amazonaws.com/php-${PHP_VERSION}-with-fpm-heroku.tar.gz"
 PHP_PATH="vendor/php"
 
+NODE_VERSION="0.6.10"
+NODE_URL=""
+NPM_VERSION="1.0.94"
+
+SCONS_VERSION="1.2.0"
+SCORN_URL=""
+
+# ----Amazon S3----
+S3_BUCKET="simpleit-heroku-builds"
+
+# ----Local folders----
+BUILD_DIR=$1
+CACHE_DIR=$2
+BIN_DIR=$(dirname $0)
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+
+# ----FUNCTIONS---------------------------------------------------------
 
 function indent() {
   c='s/^/       /'
@@ -29,26 +49,33 @@ function indent() {
   esac
 }
 
-BUILD_DIR=$1
-CACHE_DIR=$2
-BIN_DIR=$(dirname $0)
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
+run_npm() {
+  command="$1"
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
 
-#echo "BUILD_DIR: $BUILD_DIR"
-#echo "CACHE_DIR: $CACHE_DIR"
-#echo "BIN_DIR: $BIN_DIR"
-#echo "LP_DIR: $LP_DIR"
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to $command dependencies with npm"
+    exit 1
+  fi  
+}
+
+# ----PRE-INSTALL ACTIONS-----------------------------------------------
+
+echo "-----> SdZ Heroku Buildpack: Slug compilation start"
+
+# fail fast
+set -e
+set -o pipefail
 
 mkdir -p $BUILD_DIR $CACHE_DIR
 
 cd $BUILD_DIR
 
-# move app things to www
+echo "-----> Move application files into 'www' folder"
 mkdir -p $CACHE_DIR/www
 mv * $CACHE_DIR/www
 mv $CACHE_DIR/www .
 mv www/conf ./
-
 
 # keep Procfile
 if [ -f www/Procfile ]; then
@@ -60,12 +87,8 @@ if [ ! -d vendor ]; then
   mkdir vendor
 fi
 
-#echo "-> LISTFILES"
-#echo "-> Builddir:"
-#ls -lR .
-
-#echo "-> Cachedir:"
-#ls -lR $CACHE_DIR
+###TODO###
+# Use cache if no change of version of the vendors
 
 #for DIR in $NGINX_PATH $PHP_PATH ; do
 #  rm -rf $DIR
@@ -74,73 +97,76 @@ fi
 #  fi  
 #done
 
-#echo "-> LISTFILES"
-#echo "-> Builddir:"
-#ls -lR .
-#
-#echo "-> Cachedir:"
-#ls -lR $CACHE_DIR
-
-# Nginx
+# ----INSTALL SERVICES-----------------------------------------------------
+# ----Nginx------------------------------
+cd $BUILD_DIR
 
 echo "-----> Installing Nginx"
 cd ${BUILD_DIR}
 if [ ! -d $NGINX_PATH ]; then
-  echo "-----> Bundling Nginx v${NGINX_VERSION}"
+  echo "---------> Bundling Nginx v${NGINX_VERSION}"
   mkdir -p $NGINX_PATH && cd $NGINX_PATH
   curl --silent --max-time 60 --location $NGINX_URL | tar xz
 fi
+echo "---------> Moving conf files to vendor directory"
+erb conf/nginx.conf.erb > $NGINX_PATH/conf/nginx.conf
 
-# PHP
+# ----PHP--------------------------------
+cd $BUILD_DIR
+
 echo "-----> Installing PHP"
 cd ${BUILD_DIR}
 if [ ! -d $PHP_PATH ]; then
-  echo "-----> Bundling PHP v${PHP_VERSION}"
+  echo "---------> Bundling PHP v${PHP_VERSION}"
   mkdir -p $PHP_PATH && cd $PHP_PATH
   curl --silent --max-time 300 --location $PHP_URL | tar xz
 fi
-
-cd $BUILD_DIR
-
-#echo "-> LISTFILES"
-#echo "-> Builddir:"
-#ls -lR .
-
-#echo "-> Cachedir:"
-#ls -lR $CACHE_DIR
-
-# update config files
+echo "---------> Moving conf files to vendor directory"
 cp conf/php-fpm.conf $PHP_PATH/etc/php-fmp.conf
 cp conf/php.ini $PHP_PATH/php.ini
-erb conf/nginx.conf.erb > $NGINX_PATH/conf/nginx.conf
 
-cp conf/parameters.ini www/app/config/parameters.ini
+# ----END INSTALL SERVICES-------------------------------------------------
 
-# setup web script. php-cgi relies on PHP_FCGI_CHILDREN=5 PHP_FCGI_MAX_REQUESTS=1000, set in 'bin/release'
-echo "-----> Installing boot script"
+
+# ----INSTALL APPLICATION--------------------------------------------------
 cd $BUILD_DIR
 
-#mkdir -p bin
-#ln -s /app/${PHP_PATH}/bin/php bin/php
-#ln -s /app/${PHP_PATH}/sbin/php-fpm bin/php-fpm
-#ln -s /app/${NGINX_PATH}/sbin/nginx bin/nginx
+echo "-----> Installing Sf2 application"
 
+echo "---------> Moving app conf files to Sf2 configuration directory"
+cp conf/parameters.ini www/app/config/parameters.ini
+
+###TODO### Fix issue with bin/vendor install script
+#echo "---------> Install Sf2 vendors"
+#${PHP_PATH}/bin/php www/bin/vendors install
+#find www/vendor -name .git -type d | xargs rm -rf
+
+echo "---------> Install Sf2 assets"
+###FIXME### Change 'dev' environement to 'prod'
+${PHP_PATH}/bin/php www/app/console assets:install www/web --env=dev
+
+
+# ----BOOT SCRIPT----------------------------------------------------------
+
+echo "-----> Installing boot script"
 
 cat >>boot.sh <<EOF
 #!/usr/bin/env bash
 
 export PATH=/app/vendor/nginx/sbin:/app/vendor/php/bin:/app/vendor/php/sbin:/usr/local/bin:/usr/bin:/bin:$PATH
 
-echo "Copy parameters.ini file into Sf2 app config folder"
+echo "---- SdZ Heroku boot Script ----"
+
+echo "--> Copy parameters.ini file into Sf2 app config folder"
 cp /app/conf/parameters.ini /app/www/app/config/parameters.ini
 
-echo "Copy PHP & Nginx conf files into vendors directory"
+echo "--> Copy PHP & Nginx conf files into vendors directory"
 cp /app/conf/php-fpm.conf /app/vendor/php/etc/php-fpm.conf
 cp /app/vendor/php/share/php/fpm/status.html /app/status.html
 cp /app/conf/php.ini /app/vendor/php/php.ini
 erb /app/conf/nginx.conf.erb > /app/vendor/nginx/conf/nginx.conf
 
-echo "Linking Sf2 cache dir to /tmp folder"
+echo "--> Linking Sf2 cache dir to /tmp folder"
 if [ -d /app/www/app/cache ]; then
     rm -rf /app/www/app/cache
 fi
@@ -150,37 +176,29 @@ fi
 mkdir /tmp/sf-cache
 ln -s /tmp/sf-cache /app/www/app/cache
 
-echo "Enabled Sf2 logging system"
+echo "--> Enabled Sf2 logging system"
 touch /app/www/app/logs/prod.log /app/www/app/logs/dev.log
 tail -F -n 0 /app/www/app/logs/prod.log &
 tail -F -n 0 /app/www/app/logs/dev.log &
 
-echo "Enabled Nginx logging system"
+echo "--> Enabled Nginx logging system"
 touch /app/vendor/nginx/logs/access.log /app/vendor/nginx/logs/error.log
 mkdir -p client_body_temp fastcgi_temp proxy_temp scgi_temp uwsgi_temp
 tail -F -n 0 /app/vendor/nginx/logs/access.log &
 tail -F -n 0 /app/vendor/nginx/logs/error.log &
 
-echo "Enabled Php-fpm logging system"
+echo "--> Enabled PHP-FPM logging system"
 mkdir /app/vendor/php/log/
 touch /app/vendor/php/log/php-fpm.log
 tail -F -n 0 /app/vendor/php/log/php-fpm.log &
 
-echo "Booting PHP-FPM & Nginx"
+echo "--> Booting PHP-FPM & Nginx"
 php-fpm
 nginx
+
+echo "--> Done!"
 EOF
 chmod +x boot.sh
+# ----END BOOT SCRIPT------------------------------------------------------
 
-cd $BUILD_DIR
-
-#echo "-----> Install Sf2 vendors"
-#${PHP_PATH}/bin/php www/bin/vendors install
-#
-#find www/vendor -name .git -type d | xargs rm -rf
-
-echo "-----> Install Sf2 assets"
-${PHP_PATH}/bin/php www/app/console assets:install www/web
-
-
-echo "-----> Done with compile"
+echo "-----> Slug compilation ends with success!"
